### PR TITLE
Add Travis CI configuration

### PR DESCRIPTION
**Pull request by vstinner**

### CODE REVIEW

**Comment by vstinner** [comment]
I enabled Travis CI integration for ferrypick at https://travis-ci.org/

**Comment by vstinner** [comment]
Oh, the test failed on Travis CI with:

```
E       urllib.error.HTTPError: HTTP Error 503: Service Temporarily Unavailable
```

because pagure is down. My PR https://github.com/fedora-python/ferrypick/pull/1 fix this issue by mocking the download() function, to avoid depending on an external service (Pagure).

**Comment by hroncok** [comment]
I actually wanted to test out https://github.com/marketplace/actions/python-tox-on-fedora for this

**Comment by vstinner** [comment]
I rebased my PR on master. Travis CI now pass.

> I actually wanted to test out https://github.com/marketplace/actions/python-tox-on-fedora for this

I don't really care of which CI is used. I would like to have a CI on PRs, since I didn't even notice that ferrypick had tests when I created my PR :-) I don't know know how to use  https://github.com/marketplace/actions/python-tox-on-fedora.

**Comment by hroncok** [comment]
I've opened https://github.com/fedora-python/ferrypick/pull/6 instead. I don't think we need 2 CIs and I'd prefer to dogfood our own things, sorry.

**Comment by vstinner** [comment]
> I've opened #6 instead. I don't think we need 2 CIs and I'd prefer to dogfood our own things, sorry.

Sure, one CI is enough. I proposed Travis CI since it's basically the only one that I knew :-) I'm fine with python-tox-on-fedora.

**Pull request closed without merging**
